name: Deploy to AWS Amplify
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: AKIA5FCD6KQFTGNRK2MZ
          aws-secret-access-key: 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
          aws-region: us-east-1

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Deploy to AWS Amplify
        run: |
          npm install -g @aws-amplify/cli
          amplify configure --app-id d3um1l4se753hf
          amplify push --yes
